version: '2'

services:
        run:
                build: .
                volumes:
                        - .:/go/src/pefi
                tty: true
                environment:
                        - GOPATH=/go
                        - redis-host=redis
                        - redis-port=6379
                ports:
                        - 8080:8080
        redis:
                image: 'redis:alpine'

