version: '2.1'

services:
        pefi:
                build: 
                        context: .
                        dockerfile: Dockerfile.prod
                image: simonschneider/pefi-api
                environment:
                        - postgres-host=postgres
                        - postgres-port=5432
                        - redis-host=redis
                        - redis-port=6379
                ports:
                        - 22400:22400
                depends_on:
                        redis:
                                condition: service_started
                        postgres:
                                condition: service_healthy
        redis:
                image: 'redis:alpine'
        postgres:
                image: 'postgres:alpine'
                volumes:
                        - ./database:/docker-entrypoint-initdb.d/
                healthcheck:
                        test: "psql -U postgres -l | grep pefi"
                        interval: 10s

