package api

import (
	"pefi/logger"
	"pefi/router"
)

//Routes contains the gorilla mux routes of the API
var Routes = router.Routes{
	//Account Routes
	router.Route{
		"AddExternalAccount",
		"POST",
		"/accounts/external",
		router.Handler(AddExternalAccount,
			logger.HTTPLogger("Adding")),
	},
	router.Route{
		"AddInternalAccount",
		"POST",
		"/accounts/internal",
		router.Handler(AddInternalAccount,
			logger.HTTPLogger("Adding")),
	},
	router.Route{
		"GetExternalAccounts",
		"GET",
		"/accounts/external",
		GetExternalAccounts,
	},
	router.Route{
		"GetInternalAccounts",
		"GET",
		"/accounts/internal",
		GetInternalAccounts,
	},
	router.Route{
		"GetExternalAccount",
		"GET",
		"/accounts/external/{accountId}",
		GetExternalAccount,
	},
	router.Route{
		"GetInternalAccount",
		"GET",
		"/accounts/internal/{accountId}",
		GetInternalAccount,
	},
	router.Route{
		"DeleteExternalAccount",
		"DEL",
		"/accounts/external/{accountId}",
		DelExternalAccount,
	},
	router.Route{
		"DeleteInternalAccount",
		"DEL",
		"/accounts/internal/{accountId}",
		DelInternalAccount,
		//router.Handler(DelInternalAccount,
		//logger.HttpLogger),
	},
	// Label router.Routers
	router.Route{
		"AddLabel",
		"POST",
		"/labels",
		AddLabel,
	},
	router.Route{
		"GetLabels",
		"GET",
		"/labels",
		router.Handler(GetLabels,
			logger.HTTPLogger("test2")),
	},
	router.Route{
		"GetLabel",
		"GET",
		"/labels/{labelId}",
		GetLabel,
	},
	router.Route{
		"DeleteLabel",
		"DEL",
		"/labels/{labelId}",
		DelLabel,
	},
	// Transaction router.Routers
	router.Route{
		"AddTransaction",
		"POST",
		"/transactions",
		AddTransaction,
	},
	router.Route{
		"GetTransactions",
		"GET",
		"/transactions",
		GetTransactions,
	},
	router.Route{
		"GetTransaction",
		"GET",
		"/transactions/{transactionId}",
		GetTransaction,
	},
	router.Route{
		"DeleteTransaction",
		"DEL",
		"/transactions/{transactionId}",
		DelTransaction,
	},
}
